# recipes/recipe.yml
type: bootc
name: qsblue-niri-dms
# Modern BlueBuild images are bootc-based (works exactly like your current Containerfile)
image-version: 43
base-image: ghcr.io/ublue-os/silverblue-main

modules:
  - name: copr-repos
    type: copr
    repos:
      - avengemedia/dms
      - avengemedia/danklinux\
      - ublue-os/packages

  - type: rpm-ostree
    install:
      - niri
      - xwayland-satellite
      - greetd
      - greetd-tuigreet   # keep for fallback, your DMS greeter will override
      - greetd-selinux
      - qt6-qtwayland
      - xdg-desktop-portal-gnome 
      - wl-clipboard
      - network-manager-applet
      - quickshell
      - matugen
      - material-symbols-fonts
      - dms
      - dms-greeter
      - wlsunset
      - imv
      - mpv
      - nemo
      - mousepad
      - hyprpolkitagent

    remove:
      - firefox
      - firefox-langpacks
      - gnome-software
      - gnome-software-rpm-ostree
      - sddm
      - gdm
      - gnome-tour
      - yelp

  - type: files
    files:
      - source: system_files
        destination: /


  - type: script
    scripts:
      - 01-dms-and-flatpaks.sh: |
          #!/bin/bash
          set -euo pipefail

          # Add Flathub
          flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo



  - type: systemd
    enabled:
      - greetd.service


# Optional: add a description so blue-build.org dashboard looks nice
description: "QuickBlue – Niri + DankMaterialShell + DMS Greeter + Brave dev setup"